# Generated by Django 2.2.5 on 2020-02-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200225_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
